@startuml pyJiraCli_components

top to bottom direction
skinparam Linetype ortho

file "Profile data" as profile_data

package "pyProfileMgr" {
  [main]

  [Profile command] as cmd_profile
  [Profile manager] as profile_mgr
}

profile_data .down...> cmd_profile : <<flow>>

database "Jira server" as jira_server {
  file "Jira issue" as jira_issue
}

folder Filesystem {
  file "Profile data" as profile_data_files
}

main .down.> cmd_profile : <<flow>>

cmd_profile ...down.> profile_mgr : <<flow>>\n<<store/delete/update/list>>
profile_mgr ...down.> profile_data_files : <<flow>>\n<<store/delete/update/list>>
profile_mgr .down...> jira_server : <<authenticate>>

'Notes
note top of profile_data
  Server URL, server type, user API token and/or
  username/password are mandatory. The server
  certificate is optional and depends on the server type.
end note

note bottom of profile_data_files
  Server URL, server type, user API token
  and/or user and password and server certificate
  are stored in a profile folder with a unique name,
  by which the profile can be referenced later.
end note

@enduml
